/*
Universidad Abierta y a Distacia de Mexico (UnADM)
Autor: Miguel Angel Mendoza Jimenez
Matricula: ES172000597
Carrera Ingenieria en Desarrollo de Software
Materia: Programacion Orientada a Objetos III
Actividad: Evidencia de aprendizaje Unidad 1
Docente: Nora García González
Tijuana, B.C., Abril 2022 
 */
package Materiales;
// librerias a usar
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class buscarPalabraEnArchivo extends javax.swing.JDialog {
    // metodo con el que se inician los componentes con la pocion de la ventana al centro de la pantalla,
    // el titulo de la ventana y desabilitamos la edicion del TextArea y TextField
    public buscarPalabraEnArchivo(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("BUSCAR DATO EN ARCHIVO");
        txtBuscarDato.setEditable(false);
        txtAreaDatoEncontrado.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarDato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDatoEncontrado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarDato = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("El dato a buscar es:");

        txtBuscarDato.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBuscarDato.setMinimumSize(new java.awt.Dimension(6, 26));

        txtAreaDatoEncontrado.setColumns(20);
        txtAreaDatoEncontrado.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtAreaDatoEncontrado.setRows(5);
        jScrollPane1.setViewportView(txtAreaDatoEncontrado);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("El dato ingresado para búsqueda se encuentra en:");

        btnBuscarDato.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBuscarDato.setText("Buscar dato en archivo");
        btnBuscarDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDatoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel3.setText("Buscar dato en archivo de texto");

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58)
                                .addComponent(txtBuscarDato, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(btnBuscarDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarDato)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDatoActionPerformed
        // se declaran las variables a usar
        Scanner teclado = null;
        String fila;
        int numDeFila = 1;
        boolean datoEncontrado = false;
 
        // para seleccionar el archivo donde buscaremos la palabra usamos FileChooser
        // declaramos el metodo y posteriormente lo mostramos en una ventana
        JFileChooser archivo = new JFileChooser();
        archivo.showOpenDialog(archivo);

        // con JOptionPane usamos un InputDialog paar que se ingrese el texto que se desea buscar
        String buscarDato = JOptionPane.showInputDialog("Introduzca texto a buscar:");
        // el texto inresado lo guardamos dentro de un campo textField
        txtBuscarDato.setText(buscarDato);

        try {
            // se guarda la ubicacion del archivo en la variable ubicacionArchivo
            String ubicacionArchivo = archivo.getSelectedFile().getAbsolutePath();
            // se crea el objeto de tipo File que se asocia al archivo seleccionado
            File documento = new File(ubicacionArchivo);
            // se declara el scanner para poder leer el archivo
            teclado = new Scanner(documento);
            
            // se realiza uan condicion while que se ejecutara hasta que no se llegue al final de archivo
            while (teclado.hasNext()) { 
                // se lee una fila del archivo
                fila = teclado.nextLine();  
                // si la fila del archivo contiene el texto ingresado en el campo textField
                // se mostrara el resultado
                if (fila.contains(buscarDato)) {   
                    //el resultado se muestra en pantalla dentro del un textArea
                    txtAreaDatoEncontrado.setText("El documento que selecciono es: " + documento.getName()+ 
                    "\nEl dato a buscar es: " + buscarDato + "\nUbicado en la fila " + numDeFila + ": " + fila);
                    datoEncontrado = true;
                }
                // se incrementa el contador de las filas durante la ejecucion de la condicion while
                numDeFila++; 
            }
            // si el archivo seleccionado no contiene la palabra que se busca se mostrara mensaje al usuario
            if(!datoEncontrado){  
                JOptionPane.showMessageDialog(null, buscarDato + " Dato no encontrado en el archivo");
            }
        // Si existe algun error se mosatrar en pantalla al usaurio por medio de un mensaje
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, e.toString() + "Ningun archivo ha sido seleccionado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        } finally {
            if (teclado != null) {
                teclado.close();
            }
        }        
    }//GEN-LAST:event_btnBuscarDatoActionPerformed

    // se valida cierre de ventana y regreso a ventana de registro de materiales
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "   ¿Esta seguro que desea regresar "
            + "\nal registro de materiales?",
            "Regresar al registro", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            dispose();//Cierra la ventana
        }
        //En caso de que la ópcion sea no solo se cierra el cuadro de diálogo
        if (resp == JOptionPane.NO_OPTION);
        {
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarPalabraEnArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarPalabraEnArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarPalabraEnArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarPalabraEnArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                buscarPalabraEnArchivo dialog = new buscarPalabraEnArchivo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDato;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaDatoEncontrado;
    private javax.swing.JTextField txtBuscarDato;
    // End of variables declaration//GEN-END:variables
}
