/*
Universidad Abierta y a Distacia de Mexico (UnADM)
Autor: Miguel Angel Mendoza Jimenez
Matricula: ES172000597
Carrera Ingenieria en Desarrollo de Software
Materia: Programacion Orientada a Objetos III
Actividad: Evidencia de aprendizaje Unidad 1
Docente: Nora García González
Tijuana, B.C., Abril 2022 
 */
package Materiales;
// librerias a usar
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class renombrarArchivo extends javax.swing.JDialog {
    // se crea el objeto documeneto con la clase File
    File documento = new File("");
    // metodo con el que se inician los componentes con la pocion de la ventana al centro de la pantalla,
    // el titulo de la ventana 
    public renombrarArchivo(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("CAMBIAR NOMBRE ARCHIVO");
    }
    
    //Se crea método para limpiar los campos
    private void limpiar() {
        txtRutaArchivo.setText("");
        txtCambiarNombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnElegirArchivo = new javax.swing.JButton();
        txtCambiarNombre = new javax.swing.JTextField();
        btnCambiarNombre = new javax.swing.JButton();
        txtRutaArchivo = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAMBIAR NOMBRE DEL ARCHIVO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Seleccione el archivo para cambiar el nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Ingrese el nuevo nombre que tendra el archivo");

        btnElegirArchivo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnElegirArchivo.setText("Seleccionar");
        btnElegirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirArchivoActionPerformed(evt);
            }
        });

        txtCambiarNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnCambiarNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCambiarNombre.setText("Cambiar Nombre");
        btnCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarNombreActionPerformed(evt);
            }
        });

        txtRutaArchivo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCambiarNombre)
                    .addComponent(btnElegirArchivo))
                .addContainerGap())
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElegirArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarNombre))
                .addContainerGap())
        );

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(239, 239, 239))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // evento usado en el boton para seleccionar el archivo
    private void btnElegirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirArchivoActionPerformed
        // se declara el tray catch para las excepciones
        try {
            // con FileChooser seleccionaremos el arhcivo a cambiar el nombre creando un objeto
            JFileChooser elegirArchivo = new JFileChooser();
            // se abre la ventana para buscar el archivo en el explorador
            elegirArchivo.showOpenDialog(null);
            // se selecciona y guarda el archivo seleccionado
            documento = elegirArchivo.getSelectedFile();
            // mostramos la ruta en el text field
            txtRutaArchivo.setText(documento.getParent() + "\\" + documento.getName());   
        // se declara la excepcion en caso de error 
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Existe un error con el archivo " + ex);
        }
    }//GEN-LAST:event_btnElegirArchivoActionPerformed

    // validacion para cerrar la ventana
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "   ¿Esta seguro que desea regresar "
            + "\nal registro de materiales?",
            "Regresar al registro", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            dispose();//Cierra la ventana
        }
        //En caso de que la ópcion sea no solo se cierra el cuadro de diálogo
        if (resp == JOptionPane.NO_OPTION);
        {
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNombreActionPerformed
        try {
            // Se declara variable y se inicializa con los datos de la variable archivo tipo File
            // y se concatena con el campo de texto donde se ingresara el nuevo nombre y se delcara el tipo de archivo
            String nuevo = documento.getParent()+ "\\" + txtCambiarNombre.getText() + ".txt";
            // Se crea el nuevo archivo con el nombre que se coloco en el campo para cambiarlo
            File nuevoNombre = new File(nuevo);
            // con ayuda de un boolean y el metodo renameTo se pasa el nuevo nombre del archivo
            boolean cambiarNombre = documento.renameTo(nuevoNombre);
            // Se vailda si se cambio el nombre
            if (cambiarNombre==true){
            // si se cambio el nombre se muestra mensaje al usuario
            JOptionPane.showMessageDialog(null,"Se cambio el nombre del archivo con éxito");
            }else{
            // en caso de existir un error se informa al usuario tambien
            JOptionPane.showMessageDialog(null,"Existe un problema al cambiar el nombre del archivo");
        }
            // llamamos al metodo para limpiar los campos
            limpiar();
        // se declara la excepcion en caso de error 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Existe un error con el archivo " + ex);
        }
        
    }//GEN-LAST:event_btnCambiarNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(renombrarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(renombrarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(renombrarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(renombrarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                renombrarArchivo dialog = new renombrarArchivo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarNombre;
    private javax.swing.JButton btnElegirArchivo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField txtCambiarNombre;
    private javax.swing.JTextField txtRutaArchivo;
    // End of variables declaration//GEN-END:variables
}
