/*
Universidad Abierta y a Distacia de Mexico (UnADM)
Autor: Miguel Angel Mendoza Jimenez
Matricula: ES172000597
Carrera Ingenieria en Desarrollo de Software
Materia: Programacion Orientada a Objetos III
Actividad: Evidencia de aprendizaje Unidad 1
Docente: Nora García González
Tijuana, B.C., Abril 2022 
 */
package Materiales;
// librearias a usar
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class ventanaPrincipal extends javax.swing.JFrame {
    // variable para mostrar la ventana 
    ventanaMateriales mostrar;
    FondoPanel fondo = new FondoPanel();

    // metodo con el que se inician los componentes con la pocion al centro de la pantalla,
    // y el titulo de la ventana
    public ventanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("CONSTRUCTORA DEPARTAMENTAL || GESTION DE MATERIALES");
        this.setContentPane(fondo);
    }
    
    //Creamos la clase para establecer el fondo de imagen del Frame
    class FondoPanel extends JPanel {

        //Declaramos la variable
        private Image imagen;

        //Sobre escribimos el método paint y declaramos el directorio de la imagen para
        // mostrar el fondo de imagen que tendra la ventana principal
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuListaMateriales = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menú");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menuListaMateriales.setText("Materiales");
        menuListaMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaMaterialesActionPerformed(evt);
            }
        });
        jMenu1.add(menuListaMateriales);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // salida por medio del menu item se pide confirmacion al usuario por medio de un mensaje
    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "   ¿Esta seguro que desea "
                + "\nsalir del sistema?",
                "Cerrar programa", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            dispose();//Cierra la ventana 
        }
        //En caso de que la ópcion sea no solo se cierra el cuadro de diálogo
        if (resp == JOptionPane.NO_OPTION);
        {
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    // por medio del menu item se muestra la ventana materiales
    private void menuListaMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaMaterialesActionPerformed
        // se muestra la ventana
        mostrar = new ventanaMateriales(this, true);
        mostrar.setVisible(true);
    }//GEN-LAST:event_menuListaMaterialesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuListaMateriales;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
